"""add default timestamp to salesman

Revision ID: 7bedfaf3f29e
Revises: 86d20a2ce94c
Create Date: 2026-09-19 15:12:35.441932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bedfaf3f29e'
down_revision: Union[str, Sequence[str], None] = '86d20a2ce94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
