"""create salesman performance and leave tables

Revision ID: 86d20a2ce94c
Revises: 
Create Date: 2026-09-19 14:48:53.000382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d20a2ce94c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesmen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('territory', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_salesmen_id'), 'salesmen', ['id'], unique=False)
    op.create_table('leave_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_records_id'), 'leave_records', ['id'], unique=False)
    op.create_index(op.f('ix_leave_records_salesman_id'), 'leave_records', ['salesman_id'], unique=False)
    op.create_table('sales_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('target', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('achievement', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_performance_id'), 'sales_performance', ['id'], unique=False)
    op.create_index(op.f('ix_sales_performance_salesman_id'), 'sales_performance', ['salesman_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_performance_salesman_id'), table_name='sales_performance')
    op.drop_index(op.f('ix_sales_performance_id'), table_name='sales_performance')
    op.drop_table('sales_performance')
    op.drop_index(op.f('ix_leave_records_salesman_id'), table_name='leave_records')
    op.drop_index(op.f('ix_leave_records_id'), table_name='leave_records')
    op.drop_table('leave_records')
    op.drop_index(op.f('ix_salesmen_id'), table_name='salesmen')
    op.drop_table('salesmen')
    # ### end Alembic commands ###
