"""add unique constraint for salesman performance period

Revision ID: a37855302b00
Revises: 0491d9e816e1
Create Date: 2026-09-22 00:25:25.617747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37855302b00'
down_revision: Union[str, Sequence[str], None] = '0491d9e816e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_salesman_performance_period', 'sales_performance', ['salesman_id', 'period'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_salesman_performance_period', 'sales_performance', type_='unique')
    # ### end Alembic commands ###
